project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  favicon: static/bsa-favicon.png
  title: "Producing Quality Analysis" 
  # Search is good to have and works very well. But it introduces an accessibility
  # issue no matter how it is configured.
  # https://quarto.org/docs/websites/website-search.html
  # overlay gives empty button, while textbox gives empty label
  # Disabled for now until a solution is found
  search: false
  navbar:
    title: false
    logo: "static/NHSBSA logo.png"
    logo-alt: "NHS Business Services Authority"
    logo-href: "https://www.nhsbsa.nhs.uk/"
    pinned: true
    background: "#005EB8"
    collapse: false
    left:
      - href: index.qmd
        text: Playbook Home Page
      - text: "Guidance"
        menu:
          - href: guidance/01-principles/index.qmd
          - href: guidance/02-analytical-cycle/index.qmd
          - href: guidance/03-responsibilities/index.qmd
          
    right:
      - href: about.qmd
        text: "{{< iconify mdi:information-outline size=xl >}} About"
      - href: https://www.nhsbsa.nhs.uk/nhsbsa-statistics-and-data-science
        text: "{{< iconify mdi:house-outline size=xl >}} NHSBSA Data Science Home Page"
      - href: https://github.com/nhsbsa-data-analytics
        text: "{{< iconify mdi:github size=xl >}} GitHub"
      - href: https://twitter.com/nhsbsa
        text: "{{< iconify mdi:twitter size=xl >}} X (formerly Twitter)"
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - index.qmd
      - guidance/01-principles/index.qmd
      - section: "Analytical Cycle"
        contents:        
          - guidance/02-analytical-cycle/index.qmd
          - guidance/02-analytical-cycle/pages/03-customer-engagement.qmd
          - guidance/02-analytical-cycle/pages/04-analysis-design.qmd
          - guidance/02-analytical-cycle/pages/05-conducting-the-analysis.qmd
          - guidance/02-analytical-cycle/pages/06-delivery-and-approval.qmd
          - guidance/02-analytical-cycle/pages/07-approval-and-distribution.qmd
          - guidance/02-analytical-cycle/pages/08-review.qmd        
      - section: "Responsibilities"
        contents:            
          - guidance/03-responsibilities/pages/09-commissioner-responsibilities.qmd
          - guidance/03-responsibilities/pages/10-analyst-responsibilities.qmd
          - guidance/03-responsibilities/pages/11-critical-friend.qmd
    page-footer:
      left:
        - text: "Accessibility"
          href: accessibility.qmd

format:
  html:
   grid: 
    sidebar-width: 25%
   pagetitle: "Producing Quality Analysis"
   lang: en-GB
   theme: cosmo
   css: styles.css
   mainfont: "Arial"
   fontsize: 130%
   page-layout: full
   toc: true
    
execute:
  freeze: auto
