---
title: "Types of analytical model "
description: ""
---

**Policy simulation**: to better understand policy options that drive government decisions.Ministers make policy decisions. They base them on assessments of the likely cost and impact of policy choices. For example, the Intra Government Tax Benefit Model is used to analyse the distributional impact of tax and benefit changes. 

**Forecasting**: to predict the future and inform today’s policy choices. For example, demographic projections are essential to understand future cost pressures for education and healthcare. Equally, DECC use the updated Energy and Emissions Model to forecast the energy demand and emissions by fuel type and business sector under existing firm and funded policies. 

**Financial evaluation**: to better understand future liabilities or costs. For example, modelling to understand the future cost implications of current pension commitments or the future cost of decommissioning existing nuclear energy plants. 

**Procurement and commercial evaluation**: for the letting and management of large contracts, and to ensure value for money – for example, where a key service is to be contracted out as in the case of railway franchises or where a major IT upgrades/ new system is being introduced. 

**Planning**: to make workforce decisions which affect the delivery of future services. For example, these models may be used to assess the number of trainee teachers, doctors and nurses required to deliver education and healthcare into the future. 

**Science based**: to better understand and simulate the physical environment, in order to evaluate possible solutions or to mitigate potentially devastating impacts – for example, climate change and flood risk. 

**Allocation of funds**: to determine how funds allocated to departments are then distributed to, for example: local authorities, schools or across the health service. These models are essential to ensure funds are allocated properly across the country to underpin local service delivery. 

**Conceptual**: to help understand the key influences that are important to a system being modelled. A variety of problem-structuring techniques are used to develop conceptual models 

 